### ISSUE TITLE
FAQ addition for secrets manager?

### ISSUE THREAD

**Issue by jaketrent** [lecaillon/Evolve.Doc#4]
I can't tell if you support this or not... can one use the Secrets Manager to store the `Evolve.ConnectionString`?

As in:
https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=visual-studio

That would be great if it did.  Initial testing leads to believe this is not yet supported.

For instance, this command adds the secret:

```
dotnet user-secrets set ConnectionStrings:Evolve.ConnectionString "Host=localhost;Username=postgres;Password=postgres;Database=todo"
```

But when I run the app after removing `Evolve.ConnectionString` from `evolve.json`, I get "Value cannot be null" for "Parameter name: connectionString"

**Comment by lecaillon** [comment]
@jaketrent 
Thanks for the feedback :)
You are right. Secret Manager is not implemented in Evolve.
Can you please fill an issue in the main repo at: https://github.com/lecaillon/Evolve/issues/new

Then we can evaluate the opportunity to add this feature in a future release.
