### ISSUE TITLE
Documentation string on attribute EmbeddedResourceFilters

### ISSUE THREAD

**Issue by axthosarouris** [lecaillon/Evolve.Doc#7]
Double negation is confusing.

Excludes embedded migration scripts that do not start with one of these filters (separated by semicolon).

Suggestion:  "Includes embedded migration scripts that start with one of these filters (separated by semicolon)".

**Comment by lecaillon** [comment]
PR accepted :)

**Comment by lecaillon** [comment]
Thank you @axthosarouris
